# Generated by Django 4.2.7 on 2023-12-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firs_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('nickname', models.CharField(blank=True, max_length=25)),
            ],
        ),
    ]
