# Generated by Django 4.2.7 on 2023-12-04 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('poster', models.ImageField(upload_to='image')),
                ('year', models.DateField()),
                ('group_name', models.CharField(blank=True, max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='main.musician')),
                ('feat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feat', to='main.musician')),
            ],
        ),
    ]
