# Generated by Django 4.2.7 on 2023-12-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_musician_is_group_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='firs_name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='musician',
            name='last_name',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
