# Generated by Django 4.2.7 on 2023-12-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_musician_firs_name_alter_musician_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='group_name',
        ),
        migrations.AddField(
            model_name='musician',
            name='group_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
