# Generated by Django 4.2.7 on 2023-12-04 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_song_feat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grammy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.musician')),
                ('song', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.song')),
            ],
            options={
                'verbose_name': 'grammy',
                'verbose_name_plural': 'grammies',
            },
        ),
    ]
